apiVersion: aws.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-enbuild-dev #a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-enbuild-dev
      key: creds
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-enbuild-dev #a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-enbuild-dev
      key: creds